### ISSUE TITLE
[Question] Make a part of std

### ISSUE THREAD

**Issue by vanesyan** [dart-lang/http2#26]
Hello there! Great work, I been waiting for the library for a long time. Just a question, are there any plans to make the library be part of sdk?

**Comment by zoechi** [comment]
How would that make a difference?
The Dart team tries to keep the SDK as small as possible, so I'd think it's unlikely to become part of the SDK.

**Comment by jakobr-google** [comment]
More specifically, I don't think there's any *need* for this to part of the SDK.
