### ISSUE TITLE
What protocol ID(s) and negotiation(s) does this library support?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/http2#4]
For https://github.com/http2/http2-spec/wiki/Implementations

Thanks!

**Comment by sethladd** [comment]
And, I suppose this would be useful to add to the README, too. :)

**Comment by mkustermann** [comment]
Protocol negogiation: ALPN, direct
Protocol version: h2

This is already mentioned in the [library documentation](http://www.dartdocs.org/documentation/http2/0.1.0/index.html#http2/http2-transport).

**Comment by sethladd** [comment]
Thanks @mkustermann !

**Comment by sandrobilbeisi** [comment]
sorry for re-opening this,

but by reading the implementation code and comments I see that it does support the "UPGRADE" method to switch from HTTP1.1 to HTTP2

so why not add the "UPGRADE" as a protocol negotiation?

**Comment by mkustermann** [comment]
By protocol negotiation we specifically mean ALPN (application level protocol negotiation). This is only supported via the ALPN TLS extension and the protocol is negotiated before any http things are done.

Using a normal http/1.1 connection for a while and later on "upgrading" it to an http/2 connection (websockets are done in a similar way) is a different thing entirely and we have no explicit support for that atm.
